name: Compile LaTeX files and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: narainp11/tex-action:latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Compile LaTeX files to PDFs
      - name: Compile LaTeX documents
        run: |
          mkdir output
          for file in *.tex; do
            pdflatex -output-directory output "$file"
          done

      # Install GitHub CLI for creating release
      - name: Install GitHub CLI
        run: |
          apt update
          apt install -y gh

      # Configure GitHub CLI
      - name: GitHub CLI configuration
        run: echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create a new release and upload the PDFs
      - name: Create Release and Upload PDFs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="release-$(date +'%Y%m%d%H%M%S')"
          gh release create "$TAG_NAME" ./output/*.pdf --title "Release $TAG_NAME" --notes "Automated release of compiled PDF documents"
